# required for building jre_lwjgl3glfw with Java 8 while using plugins in app_pojavlauncher that require Java 11
org.gradle.configureondemand=true

android.useAndroidX=true
android.bundle.language.enableSplit=false
# Increase Gradle daemon RAM allocation
org.gradle.jvmargs=-Xmx4096M
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/usr/lib/jvm/java-8-openjdk-amd64,/usr/lib/jvm/java-1.8.0-openjdk-amd64
android.nonTransitiveRClass=false
android.nonFinalResIds=false
